#!url=https://github.com/zbtang/LittleRocketConfig/raw/main/modules/qqmusic/qqmusic.module
#!name=QQ音乐
#!desc=屏蔽QQ音乐广告

[Rule]
# 屏蔽广告域名
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,ad.tencentmusic.com,REJECT
DOMAIN-SUFFIX,ads.privacy.qq.com,REJECT
DOMAIN,adstats.tencentmusic.com,REJECT
DOMAIN,ad.tencentmusic.com,REJECT
DOMAIN,adcdn.tencentmusic.com,REJECT
DOMAIN,adcdn6.tencentmusic.com,REJECT
DOMAIN,adexpo.tencentmusic.com,REJECT
DOMAIN,adclick.tencentmusic.com,REJECT
DOMAIN,otheve.beacon.qq.com,REJECT
DOMAIN,monitor.music.qq.com,REJECT
DOMAIN,stat.y.qq.com,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,tmeadquic.y.qq.com,REJECT
DOMAIN,oth.str.mdt.qq.com,REJECT
DOMAIN,h.trace.qq.com,REJECT
DOMAIN,sdk.e.qq.com,REJECT
DOMAIN,p.l.qq.com,REJECT
DOMAIN,us.l.qq.com,REJECT
DOMAIN,tangram.e.qq.com,REJECT
DOMAIN,tmeadbak.y.qq.com,REJECT
DOMAIN-SUFFIX,imtmp.net,REJECT